### PR TITLE
Added plaidRef

### PR DESCRIPTION
**Pull request by zachrnolan**
Allows us to access the WebView to do things like reload()

### CODE REVIEW

**Comment by catalinmiron** [comment]
Hi @zachrnolan,

Thanks for making this PR. You can do send `ref` as prop without this change, because we `spread` the props and so if you're sending `<PlaidLink ref={ref => this.plaidRef = ref} />` this should work out of the box.

Please ping me here in case this is not working for you. Thanks!

**Comment by zachrnolan** [comment]
Hi @catalinmiron -

I did try that first and it wasn't working for me. I don't think it likes when you pass a prop called `ref`. Does it work for you?

**Comment by catalinmiron** [comment]
@zachrnolan for some reason the `...this.props` is not working. Could you please add the following

```
import React, { Component } from 'react';
import { WebView } from 'react-native';
import { PropTypes } from 'prop-types';
import omit from 'object.omit';

class PlaidAuthenticator extends Component {
  render() {
    const {
      publicKey,
      selectAccount,
      env,
      product,
      clientName,
      webhook,
      style,
      token
    } = this.props;

    let uri = `https://cdn.plaid.com/link/v2/stable/link.html?key=${
      publicKey
    }&apiVersion=v2&env=${env}&product=${product}&clientName=${
      clientName
    }&isWebView=true&isMobile=true&webhook=${webhook}&selectAccount=${
      selectAccount
    }`;
    uri = token !== undefined ? `${uri}&token=${token}` : uri;

    return (
      <WebView
        {...omit(this.props, [
          'publicKey',
          'selectAccount',
          'env',
          'product',
          'clientName',
          'webhook',
          'token',
          'ref'
        ])}
        ref={this.props.plaidRef}
        source={{ uri }}
        onMessage={this.onMessage}
      />
    );
  }

  onMessage = e => {
    /*
      Response example for success
      {
        "action": "plaid_link-undefined::connected",
        "metadata": {
          "account": {
            "id": null,
            "name": null
          },
          "account_id": null,
          "public_token": "public-sandbox-e697e666-9ac2-4538-b152-7e56a4e59365",
          "institution": {
            "name": "Chase",
            "institution_id": "ins_3"
          }
        }
      }
    */

    this.props.onMessage(JSON.parse(e.nativeEvent.data));
  };
}

PlaidAuthenticator.defaultProps = {
  publicKey: PropTypes.string.isRequired,
  onMessage: PropTypes.func.isRequired,
  env: PropTypes.string.isRequired,
  product: PropTypes.string.isRequired,
  clientName: PropTypes.string,
  webhook: PropTypes.string,
  plaidRef: PropTypes.func
};

PlaidAuthenticator.defaultProps = {
  clientName: '',
  webhook: '',
  plaidRef: () => {}
};

export default PlaidAuthenticator;
```

Thanks!

Snack: https://snack.expo.io/@catalinmiron/plaidlink-+-ref

**Comment by catalinmiron** [comment]
Done in #6. Thanks @zachrnolan for reporting it.

**Pull request closed without merging**
