### PR TITLE
PropTypes does not belong to react anymore

### PR DESCRIPTION
**Pull request by lucascarvalho**
Add prop-types package to peerDependencies.

### CODE REVIEW

**Comment by plondon** [comment]
Thanks @lucascarvalho this fixed an issue I was having getting started!

**Comment by catalinmiron** [comment]
Thanks @lucascarvalho for contribution. I'm going to publish a new version asap. 👍

**Comment by plondon** [comment]
Thanks for your work @catalinmiron!

**Comment by catalinmiron** [comment]
@plondon no worries. I published `1.2.0`on npm. Let me know if you need anything else. Thanks!

**Pull request merged**
